'use strict';

// tests for coloreCavalloNapoleone
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('coloreCavalloNapoleone', '/handler.js', 'coloreCavalloNapoleone');

describe('coloreCavalloNapoleone', () => {
  before((done) => {
    done();
  });

  it('should be Bianco', async () => {
    const response = await wrapped.run({});
    expect(response.statusCode).to.be.equal(200);
    expect(JSON.parse(response.body).message).to.be.equal('Blu');
  });
});
